#services:
#  db:
#    image: mysql:latest
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'rapstartup'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'rakaadli'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'qawsedrf'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'qawsedrf'
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - '3306:3306'
#    expose:
#      # Opens port 3306 on the container
#      - '3306'
#      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql
## Names our volume
#volumes:
#  my-db:

version: '3.7'

services:

  #docker run --name rapstartup-go -it -p 8080:8080 --network rapstartup-network rapstartup
  rapstartup-go:
    build: .
    environment:
      - PORT=8080
      - DSN=root:@tcp(rapstartup-mariadb:3306)/rapstartup?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - 8080:8080
    networks:
      - rapstartup-network
    restart: on-failure
    depends_on:
      - rapstartup-mariadb


  #docker run --name rapstartup-mariadb -it -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -v D:\dev\docker-volume\rapstartup-maria-db:/var/lib/mysql --network rapstartup-network mariadb
  rapstartup-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306
    volumes:
      - D:\dev\docker-volume-two\rapstartup-maria-db:/var/lib/mysql
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - rapstartup-network

networks:
  rapstartup-network: